In [26]:
#Data Creation
import numpy as np
students=np.array([[1,2,3],[4,5,6]])
subjects=np.array([[7,8,9],[0,11,12]])
marks=np.array([[10,20,30],[40,50,60]])
print(students)
print(subjects)
print(marks)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [ 0 11 12]]
[[10 20 30]
 [40 50 60]]


In [27]:
#Data Exploration
print(students.ndim)
print(subjects.ndim)
print(marks.ndim)

2
2
2


In [28]:
print(students.size)
print(subjects.size)
print(marks.size)

6
6
6


In [29]:
print(students.shape)
print(subjects.shape)
print(marks.shape)

(2, 3)
(2, 3)
(2, 3)


In [30]:
#Data Transformation
print(students.reshape(1,3,2))
print(subjects.reshape(1,3,2))
print(marks.reshape(1,3,2))

[[[1 2]
  [3 4]
  [5 6]]]
[[[ 7  8]
  [ 9  0]
  [11 12]]]
[[[10 20]
  [30 40]
  [50 60]]]


In [31]:
print(students.T)
print(subjects.T)
print(marks.T)


[[1 4]
 [2 5]
 [3 6]]
[[ 7  0]
 [ 8 11]
 [ 9 12]]
[[10 40]
 [20 50]
 [30 60]]


In [32]:
print(np.flip(students))
print(np.flip(subjects))
print(np.flip(marks))

[[6 5 4]
 [3 2 1]]
[[12 11  0]
 [ 9  8  7]]
[[60 50 40]
 [30 20 10]]


In [33]:
#Data Combination
students_1=np.array([[7,8,9],[10,11,12]])
subjects_1=np.array([[13,14,15],[16,17,18]])
a=np.concatenate((students, students_1))
b=np.concatenate((subjects,subjects_1))
print(a)
print(b)
new_arr=np.concatenate((a,b))
print(new_arr.ravel())


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [ 0 11 12]
 [13 14 15]
 [16 17 18]]
[ 1  2  3  4  5  6  7  8  9 10 11 12  7  8  9  0 11 12 13 14 15 16 17 18]


In [34]:
#split
new_arr1=new_arr.reshape(-1)
print(new_arr1)
np.split(new_arr1,12)

[ 1  2  3  4  5  6  7  8  9 10 11 12  7  8  9  0 11 12 13 14 15 16 17 18]


[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12]),
 array([7, 8]),
 array([9, 0]),
 array([11, 12]),
 array([13, 14]),
 array([15, 16]),
 array([17, 18])]

In [35]:
#Data Modification
#update
a_1=marks.copy()
print(a_1)
a_1[0][2]=70
print(a_1)

[[10 20 30]
 [40 50 60]]
[[10 20 70]
 [40 50 60]]


In [36]:
#remove
a_1.reshape(-1)
np.delete(a_1,3)


array([10, 20, 70, 50, 60])

In [37]:
#unique
print(new_arr1)
np.unique(new_arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12  7  8  9  0 11 12 13 14 15 16 17 18]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [38]:
#Data Type Handling
print(new_arr1.dtype)
new_arr2=new_arr1.astype(dtype=float)
print(new_arr2)

int64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.  7.  8.  9.  0. 11. 12.
 13. 14. 15. 16. 17. 18.]


In [42]:
#Copy & View Behaviour
Subj=subjects.copy()
print(Subj)
new_Subj=Subj.ravel()
new_Subj[2]=16
print(new_Subj)
#view
new_Subj.view()
new_arr.view()




[[ 7  8  9]
 [ 0 11 12]]
[ 7  8 16  0 11 12]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [ 0, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])